INSERT INTO words (id, answer, clue, category, difficulty) VALUES
  ('w01', 'MESSI', 'Ganador de ocho Balones de Oro, campeón del Mundial 2022 con Argentina (apellido)', 'jugadores', 'easy'),
  ('w02', 'MARADONA', 'Autor del gol de ''la Mano de Dios'' ante Inglaterra en el Mundial 1986 (apellido)', 'jugadores', 'easy'),
  ('w03', 'PELE', 'Único futbolista en ganar tres Copas del Mundo como jugador: 1958, 1962 y 1970 (apodo)', 'jugadores', 'easy'),
  ('w04', 'ZIDANE', 'Expulsado en la final del Mundial 2006 por un cabezazo a Materazzi (apellido)', 'jugadores', 'medium'),
  ('w05', 'CRUYFF', 'Ícono de la ''Naranja Mecánica'' neerlandesa del Mundial 1974 (apellido)', 'jugadores', 'medium'),
  ('w06', 'BECKENBAUER', 'Ganó el Mundial con Alemania como jugador en 1974 y como director técnico en 1990 (apellido)', 'jugadores', 'hard'),
  ('w07', 'RONALDINHO', 'Balón de Oro 2005, brasileño de sonrisa característica (nombre artístico)', 'jugadores', 'easy'),
  ('w08', 'KAKA', 'Balón de Oro 2007, mediocampista brasileño (nombre artístico)', 'jugadores', 'medium'),
  ('w09', 'NEYMAR', 'Máximo goleador histórico de la selección de Brasil (apellido)', 'jugadores', 'easy'),
  ('w10', 'MBAPPE', 'Campeón del Mundial 2018 con Francia siendo aún adolescente (apellido)', 'jugadores', 'easy'),
  ('w11', 'CRISTIANO', 'Máximo goleador histórico de la Champions League (nombre de pila)', 'jugadores', 'easy'),
  ('w12', 'BUFFON', 'Arquero italiano campeón del Mundial 2006, símbolo histórico de la Juventus (apellido)', 'jugadores', 'medium'),
  ('w13', 'CASILLAS', 'Arquero y capitán de España, campeón del Mundial 2010 (apellido)', 'jugadores', 'medium'),
  ('w14', 'INIESTA', 'Autor del gol que le dio a España el título del Mundial 2010 (apellido)', 'jugadores', 'medium'),
  ('w15', 'XAVI', 'Mediocampista español, pieza clave del ''tiki-taka'' campeón del Mundial 2010 (nombre de pila)', 'jugadores', 'medium'),
  ('w16', 'MODRIC', 'Balón de Oro 2018, capitán de la selección de Croacia (apellido)', 'jugadores', 'medium'),
  ('w17', 'SUAREZ', 'Delantero uruguayo que mordió a Chiellini en el Mundial 2014 (apellido)', 'jugadores', 'easy'),
  ('w18', 'CAVANI', 'Delantero uruguayo apodado ''el Matador'' (apellido)', 'jugadores', 'medium'),
  ('w19', 'HIGUAIN', 'Delantero argentino que falló un mano a mano clave en la final del Mundial 2014 (apellido)', 'jugadores', 'medium'),
  ('w20', 'AGUERO', 'Autor del gol agónico que le dio el título 2011-12 al Manchester City (apellido)', 'jugadores', 'easy'),
  ('w21', 'KLOSE', 'Máximo goleador histórico en la historia de los Mundiales, con 16 goles (apellido)', 'jugadores', 'hard'),
  ('w22', 'PANENKA', 'Apellido del checoslovaco que inventó la técnica de penal picado al medio, en la Eurocopa 1976', 'terminos', 'hard'),
  ('w23', 'URUGUAY', 'País campeón del primer Mundial de la historia, en 1930', 'selecciones', 'easy'),
  ('w24', 'BRASIL', 'Único país con cinco títulos mundiales', 'selecciones', 'easy'),
  ('w25', 'ARGENTINA', 'País campeón del Mundial en 1978, 1986 y 2022', 'selecciones', 'easy'),
  ('w26', 'ALEMANIA', 'Campeón del Mundial 2014, tras golear 7-1 al local en semifinales', 'selecciones', 'easy'),
  ('w27', 'ITALIA', 'Campeón del Mundial 2006 tras vencer a Francia en la tanda de penales', 'selecciones', 'easy'),
  ('w28', 'FRANCIA', 'Campeón del Mundial 1998 como local y del Mundial 2018 en Rusia', 'selecciones', 'easy'),
  ('w29', 'INGLATERRA', 'Campeón del Mundial 1966, disputado en su propio país', 'selecciones', 'easy'),
  ('w30', 'ESPANA', 'País campeón del Mundial 2010 en Sudáfrica', 'selecciones', 'easy'),
  ('w31', 'HOLANDA', 'Subcampeón del Mundial en 1974, 1978 y 2010, sin haber ganado ninguno', 'selecciones', 'medium'),
  ('w32', 'CROACIA', 'Subcampeón del Mundial 2018, con Modric como capitán', 'selecciones', 'medium'),
  ('w33', 'COLOMBIA', 'Selección de ''la Tricolor'' que llegó a cuartos de final del Mundial 2014', 'selecciones', 'medium'),
  ('w34', 'CHILE', 'Selección bicampeona de la Copa América en 2015 y 2016', 'selecciones', 'medium'),
  ('w35', 'PARAGUAY', 'Selección guaraní que llegó a cuartos de final del Mundial 2010', 'selecciones', 'hard'),
  ('w36', 'PERU', 'Selección campeona de la Copa América en 1975', 'selecciones', 'hard'),
  ('w37', 'MEXICO', 'País que fue sede del Mundial en dos ocasiones: 1970 y 1986', 'selecciones', 'medium'),
  ('w38', 'PORTUGAL', 'País campeón de la Eurocopa 2016, con Cristiano Ronaldo', 'selecciones', 'easy'),
  ('w39', 'BELGICA', 'Selección europea conocida como ''los Diablos Rojos''', 'selecciones', 'medium'),
  ('w40', 'OFFSIDE', 'Infracción por recibir la pelota adelantado a la última línea defensiva (término en inglés)', 'terminos', 'easy'),
  ('w41', 'PENAL', 'Tiro que se ejecuta a once metros del arco tras una falta dentro del área', 'terminos', 'easy'),
  ('w42', 'ARQUERO', 'Jugador que defiende el arco; único que puede usar las manos dentro del área propia', 'terminos', 'easy'),
  ('w43', 'DELANTERO', 'Jugador cuya función principal es convertir goles', 'terminos', 'easy'),
  ('w44', 'MEDIOCAMPISTA', 'Jugador que conecta la defensa con el ataque', 'terminos', 'easy'),
  ('w45', 'ARBITRO', 'Encargado de hacer cumplir el reglamento dentro de la cancha', 'terminos', 'easy'),
  ('w46', 'TARJETA', 'Cartulina que muestra el árbitro para amonestar o expulsar a un jugador', 'terminos', 'easy'),
  ('w47', 'CORNER', 'Tiro de esquina que se cobra cuando la pelota sale por la línea de fondo tocada por un defensor', 'terminos', 'easy'),
  ('w48', 'LATERAL', 'Defensor que juega por las bandas de la cancha', 'terminos', 'medium'),
  ('w49', 'TRAVESANO', 'Palo horizontal que une los dos verticales del arco', 'terminos', 'medium'),
  ('w50', 'HINCHA', 'Fanático que sigue y alienta a un equipo de fútbol', 'terminos', 'easy'),
  ('w51', 'CLASICO', 'Nombre que recibe el partido entre los dos rivales históricos de una ciudad o país', 'terminos', 'easy'),
  ('w52', 'MUNDIAL', 'Torneo de selecciones que organiza la FIFA cada cuatro años', 'torneos', 'easy'),
  ('w53', 'LIBERTADORES', 'Máximo torneo de clubes de Sudamérica', 'torneos', 'medium'),
  ('w54', 'CHAMPIONS', 'Máximo torneo de clubes de Europa', 'torneos', 'easy'),
  ('w55', 'BALONDEORO', 'Premio anual al mejor jugador del mundo, otorgado por la revista France Football (sin espacios)', 'premios', 'medium'),
  ('w56', 'HATTRICK', 'Término usado cuando un jugador anota tres goles en un mismo partido', 'terminos', 'medium'),
  ('w57', 'PICHICHI', 'Nombre del trofeo al máximo goleador de la liga española', 'premios', 'hard'),
  ('w58', 'ESTADIO', 'Recinto donde se disputan los partidos de fútbol', 'terminos', 'easy'),
  ('w59', 'SILBATO', 'Instrumento que usa el árbitro para marcar inicio, final e infracciones', 'terminos', 'medium'),
  ('w60', 'VESTUARIO', 'Lugar donde los jugadores se cambian antes y después del partido', 'terminos', 'medium'),
  ('w61', 'BANQUILLO', 'Lugar donde se sientan los suplentes y el cuerpo técnico durante el partido', 'terminos', 'medium'),
  ('w62', 'GOLEADOR', 'Nombre que recibe el jugador que más goles convierte', 'terminos', 'easy'),
  ('w63', 'CAPITAN', 'Jugador que porta el brazalete y representa al equipo ante el árbitro', 'terminos', 'easy'),
  ('w64', 'AMISTOSO', 'Partido que no cuenta para ninguna competencia oficial', 'terminos', 'easy'),
  ('w65', 'PROMOCION', 'Serie de partidos que define un ascenso o descenso de categoría entre dos equipos', 'terminos', 'hard');
