INSERT INTO words (id, answer, clue, category, difficulty) VALUES
  ('w69', 'MEAZZA', 'Bicampeón del mundo italiano en 1934 y 1938 que da nombre al célebre estadio milanés', 'jugadores', 'hard'),
  ('w70', 'SCHMEICHEL', 'Arquero danés clave en el Triplete del Manchester United en 1999 y campeón de la Eurocopa 1992', 'jugadores', 'hard'),
  ('w71', 'FONTAINE', 'Delantero francés que ostenta el récord histórico de más goles anotados en una sola Copa del Mundo (13 en 1958)', 'jugadores', 'hard'),
  ('w72', 'SENEGAL', 'Selección africana conocida como los ''Leones de la Teranga'', descollante en el Mundial 2002', 'selecciones', 'hard'),
  ('w73', 'HUNGRIA', 'Selección subcampeona mundial en 1954 cuya mítica generación fue apodada los ''Magiares Poderosos''', 'selecciones', 'hard'),
  ('w74', 'NIGERIA', 'Selección africana apodada las ''Águilas Súper Verdes'', campeona del torneo olímpico de fútbol en Atlanta 1996', 'selecciones', 'hard'),
  ('w75', 'CATENACCIO', 'Estructura táctica defensiva con uso de líbero popularizada por clubes italianos en la década de 1960', 'terminos', 'hard'),
  ('w76', 'RABONA', 'Recurso técnico para golpear el balón cruzando la pierna ejecutora por detrás de la pierna de apoyo', 'terminos', 'hard'),
  ('w77', 'OLIMPICO', 'Denominación del gol anotado directamente desde el saque de esquina sin intervención de ningún otro jugador', 'terminos', 'hard'),
  ('w78', 'SUDAMERICANA', 'Segundo torneo interclubes de mayor prestigio organizado por la Conmebol desde el año 2002', 'torneos', 'hard'),
  ('w79', 'EUROCOPA', 'Principal competición de selecciones europeas organizada por la UEFA cada cuatro años desde 1960', 'torneos', 'hard'),
  ('w80', 'YASHIN', 'Galardón entregado por France Football al guardameta más destacado del año, bautizado en honor a la ''Araña Negra''', 'premios', 'hard'),
  ('w81', 'PUSKAS', 'Distinción anual conferida por la FIFA al futbolista que convierte el gol de mejor factura estética de la temporada', 'premios', 'hard'),
  ('w82', 'NOTTINGHAM', 'Histórico club inglés que conquistó dos Copas de Europa de manera consecutiva en 1979 y 1980', 'clubes', 'hard'),
  ('w83', 'FEYENOORD', 'Club neerlandés con sede en Róterdam que fue el primer equipo de su país en ganar la Copa de Europa en 1970', 'clubes', 'hard'),
  ('w84', 'KOPKE', 'Portero alemán héroe en los penaltis de semifinales de la Eurocopa 1996 ante Inglaterra', 'jugadores', 'hard'),
  ('w85', 'FRANCESCOLI', 'Famoso mediapunta uruguayo apodado El Príncipe, gran ídolo de infancia de Zinedine Zidane', 'jugadores', 'hard'),
  ('w86', 'KANOUTE', 'Delantero franco-maliense galardonado como Futbolista Africano del Año 2007 y multicampeón con el Sevilla FC', 'jugadores', 'hard'),
  ('w87', 'SURINAM', 'Selección sudamericana que por razones históricas y competitivas compite en la confederación de Concacaf', 'selecciones', 'hard'),
  ('w88', 'CAMERUN', 'Selección africana conocida como los Leones Indomables, primera de su continente en alcanzar cuartos de final mundiales en 1990', 'selecciones', 'hard'),
  ('w89', 'TAHITI', 'Selección oceánica que dio la gran sorpresa al ganar la Copa de Naciones de la OFC 2012 y clasificar a la Confederaciones 2013', 'selecciones', 'hard'),
  ('w90', 'GAMBETTA', 'Expresión rioplatense utilizada para describir un regate rápido, hábil e impredecible en espacios reducidos', 'terminos', 'hard'),
  ('w91', 'PALOMITA', 'Acrobático remate de cabeza en el que el futbolista se lanza horizontalmente por los aires para conectar el balón', 'terminos', 'hard'),
  ('w92', 'CHANFLE', 'Término popular para designar la rosca o efecto curvo impreso al balón al ser pateado con el perfil del pie', 'terminos', 'hard'),
  ('w93', 'RECOPA', 'Antiguo torneo europeo oficial (1960-1999) en el que se enfrentaban los campeones de las copas nacionales de cada país', 'torneos', 'hard'),
  ('w94', 'INTERTOTO', 'Antigua competición estival de clubes europeos organizada por la UEFA que otorgaba billetes de clasificación a la Copa de la UEFA', 'torneos', 'hard'),
  ('w95', 'GOLDENBOY', 'Premio otorgado anualmente por el periódico italiano Tuttosport al mejor futbolista sub-21 que juega en Europa', 'premios', 'hard'),
  ('w96', 'ZAMORA', 'Trofeo entregado en España desde 1959 al guardameta que encaja menos goles durante la temporada de LaLiga', 'premios', 'hard'),
  ('w97', 'PARTIZAN', 'Histórico club de Belgrado que se convirtió en el primer equipo de Europa del Este en disputar la final de la Copa de Europa en 1966', 'clubes', 'hard'),
  ('w98', 'MALMO', 'Club sueco que alcanzó sorpresivamente la final de la Copa de Europa en 1979', 'clubes', 'hard'),
  ('w99', 'LITMANEN', 'Mítico mediapunta finlandés leyenda del Ajax en los noventa y apodado ''El Rey''', 'jugadores', 'hard'),
  ('w100', 'KUBALA', 'Leyenda hispano-húngara del FC Barcelona cuya enorme popularidad motivó la construcción del Camp Nou', 'jugadores', 'hard'),
  ('w101', 'MAGICO', 'Apodo del genial futbolista salvadoreño González, figura de culto en el Cádiz en los años ochenta', 'jugadores', 'hard'),
  ('w102', 'COREADELNORTE', 'Selección asiática que protagonizó una enorme sorpresa al eliminar a Italia en la fase de grupos del Mundial de 1966', 'selecciones', 'hard'),
  ('w103', 'HAITI', 'Selección caribeña que logró una histórica clasificación y participación en el Mundial de Alemania 1974', 'selecciones', 'hard'),
  ('w104', 'ZAMBIA', 'Selección africana que conquistó heroicamente la Copa Africana de Naciones en 2012 en Libreville', 'selecciones', 'hard'),
  ('w105', 'FOLHASECA', 'Técnica de disparo con efecto descendente repentino popularizada por el brasileño Didi en los años cincuenta', 'terminos', 'hard'),
  ('w106', 'ESCORPION', 'Acrobática maniobra de despeje o remate realizada proyectando los talones por encima de la espalda', 'terminos', 'hard'),
  ('w107', 'ENGANCHE', 'Término sudamericano para definir al clásico mediapunta o diez organizador de juego', 'terminos', 'hard'),
  ('w108', 'MITROPA', 'Pionero torneo internacional europeo de clubes de Europa Central disputado entre 1927 y 1992', 'torneos', 'hard'),
  ('w109', 'KIRIN', 'Histórico torneo amistoso internacional de selecciones disputado anualmente en Japón desde 1978', 'torneos', 'hard'),
  ('w110', 'BRAVO', 'Premio otorgado por la revista Guerin Sportivo al mejor futbolista joven de Europa entre 1978 y 2015', 'premios', 'hard'),
  ('w111', 'THEBEST', 'Denominación oficial de los galardones individuales entregados anualmente por la FIFA desde 2016', 'premios', 'hard'),
  ('w112', 'STEAUA', 'Club rumano que ganó la Copa de Europa de 1986 tras vencer al Barcelona sin encajar goles en la tanda de penaltis', 'clubes', 'hard'),
  ('w113', 'MAGDEBURGO', 'Único club de la extinta República Democrática Alemana en ganar un título europeo, la Recopa de 1974', 'clubes', 'hard'),
  ('w114', 'SINDELAR', 'Mítico delantero austriaco de los años 30 apodado el Hombre de Papel, máxima estrella del Wunderteam', 'jugadores', 'hard'),
  ('w115', 'BLOKHIN', 'Legendario delantero soviético del Dinamo de Kiev ganador del Balón de Oro en 1975', 'jugadores', 'hard'),
  ('w116', 'ALTAFINI', 'Delantero ítalo-brasileño apodado Mazzola que ostentó durante décadas el récord de 14 goles en una edición de Copa de Europa', 'jugadores', 'hard'),
  ('w117', 'MADAGASCAR', 'Selección africana apodada los Barea que alcanzó sorpresivamente los cuartos de final en su debut en la Copa Africana 2019', 'selecciones', 'hard'),
  ('w118', 'COMORAS', 'Selección africana conocida como los Celacantos que clasificó por primera vez a la Copa Africana en 2021 alcanzando octavos', 'selecciones', 'hard'),
  ('w119', 'LUXEMBURGO', 'Selección europea conocida como los Leones Rojos, uno de los miembros fundadores de la UEFA con más de cuatrocientos partidos oficiales', 'selecciones', 'hard'),
  ('w120', 'CUAUHTEMINA', 'Maniobra de habilidad creada por Cuauhtémoc Blanco saltando entre dos rivales con el balón aprisionado entre los tobillos', 'terminos', 'hard'),
  ('w121', 'VERROU', 'Sistema táctico defensivo diseñado en Suiza en los años 30 por Karl Rappan, antecedente directo del catenaccio', 'terminos', 'hard'),
  ('w122', 'TRIVELA', 'Recurso técnico que consiste en golpear el balón con la parte exterior del pie para darle efecto curvo hacia afuera', 'terminos', 'hard'),
  ('w123', 'ARTEMIOFRANCHI', 'Trofeo oficial disputado en 1985 y 1993 entre los campeones de la Copa América y la Eurocopa, antecedente de la Finalissima', 'torneos', 'hard'),
  ('w124', 'MERCONORTE', 'Competición oficial de clubes disputada entre 1998 y 2001 por equipos del norte de Sudamérica y la Concacaf', 'torneos', 'hard'),
  ('w125', 'ONZEDOR', 'Galardón individual otorgado desde 1976 por la revista francesa Onze Mondial al mejor futbolista en Europa', 'premios', 'hard'),
  ('w126', 'PROVERCELLI', 'Histórico club italiano del Piamonte que conquistó siete scudettos entre 1908 y 1922', 'clubes', 'hard'),
  ('w127', 'MECHELEN', 'Club belga que sorprendió al fútbol europeo al conquistar la Recopa de Europa en 1988 tras vencer al Ajax en la final', 'clubes', 'hard'),
  ('w128', 'HIDEGKUTI', 'Delantero húngaro del legendario ''Equipo de Oro'' que revolucionó la posición de falso nueve en el histórico 6-3 ante Inglaterra en 1953.', 'jugadores', 'hard'),
  ('w129', 'SCIREA', 'Elegante defensor italiano campeón del mundo en 1982 e ídolo de la Juventus, célebre por su juego limpio y jamás haber recibido una tarjeta roja.', 'jugadores', 'hard'),
  ('w130', 'CURAZAO', 'Selección caribeña afiliada a la CONCACAF que sorprendió al conquistar la Copa del Caribe en 2017 bajo la dirección de Remko Bicentini.', 'selecciones', 'hard'),
  ('w131', 'SANMARINO', 'Selección europea de la UEFA que en 2024 logró romper una racha de dos décadas sin victorias al vencer oficialmente a Liechtenstein.', 'selecciones', 'hard'),
  ('w132', 'MAURITANIA', 'Selección africana apodada ''los Almorávides'' que logró clasificarse por primera vez en su historia a la Copa Africana de Naciones en 2019.', 'selecciones', 'hard'),
  ('w133', 'CHALACA', 'Término empleado principalmente en Perú para denominar el tiro o remate acrobático de espalda al arco conocido también como chilena.', 'terminos', 'hard'),
  ('w134', 'TOULON', 'Prestigioso torneo internacional no oficial para selecciones juveniles que se celebra anualmente en la Costa Azul francesa desde 1967.', 'torneos', 'hard'),
  ('w135', 'MERCOSUR', 'Extinto torneo oficial organizado por la CONMEBOL entre 1998 y 2001 disputado exclusivamente por clubes del Cono Sur sudamericano.', 'torneos', 'hard'),
  ('w136', 'KOPA', 'Galardón anual otorgado por France Football durante la gala del Balón de Oro al mejor futbolista del mundo menor de 21 años.', 'premios', 'hard'),
  ('w137', 'DUKLA', 'Club militar histórico de Praga que dominó el fútbol checoslovaco y alcanzó las semifinales de la Copa de Europa en 1967.', 'clubes', 'hard'),
  ('w138', 'TORINO', 'Club italiano cuyo penta-campeón equipo de los años 40, conocido como el ''Grande Torino'', falleció trágicamente en la tragedia de Superga.', 'clubes', 'hard'),
  ('w139', 'BICAN', 'Delantero austro-checo con más de 800 goles oficiales reconocidos en el siglo XX', 'jugadores', 'hard'),
  ('w140', 'CEULEMANS', 'Mítico capitán y mediocampista belga semifinalista en el Mundial de México 1986', 'jugadores', 'hard'),
  ('w141', 'SAVICEVIC', 'Mediapunta montenegrino apodado El Genio, estrella del Milan campeón europeo en 1994', 'jugadores', 'hard'),
  ('w142', 'LIECHTENSTEIN', 'Principado europeo cuya selección disputa sus encuentros como local en el Rheinpark Stadion de Vaduz', 'selecciones', 'hard'),
  ('w143', 'BENIN', 'Selección africana conocida históricamente como Dahomey y apodada Las Guepardos', 'selecciones', 'hard'),
  ('w144', 'CARABAO', 'Denominación comercial de la Copa de la Liga de Inglaterra desde 2017', 'torneos', 'hard'),
  ('w145', 'COPACONMEBOL', 'Torneo de clubes de Sudamérica disputado entre 1992 y 1999, antecesor de la Sudamericana', 'torneos', 'hard'),
  ('w146', 'HONVED', 'Histórico club de Budapest que constituyó la base de la legendaria selección húngara de los cincuenta', 'clubes', 'hard'),
  ('w147', 'NETZER', 'Volante alemán del Real Madrid en los 70 famoso por su gran visión de juego y elegancia', 'jugadores', 'hard'),
  ('w148', 'SAROSI', 'Legendario delantero húngaro subcampeón mundial en 1938 y estrella del Ferencváros', 'jugadores', 'hard'),
  ('w149', 'SCHIAFFINO', 'Mítico mediapunta uruguayo héroe del Maracanazo en 1950 y estrella del Milan', 'jugadores', 'hard'),
  ('w150', 'GOLDEORO', 'Regla en la que el primer tanto marcado durante la prórroga finalizaba el partido de inmediato', 'terminos', 'hard'),
  ('w151', 'LATINA', 'Copa disputada en los cincuenta por campeones ibéricos, franceses e italianos', 'torneos', 'hard'),
  ('w152', 'PENAROL', 'Mítico club uruguayo pentacampeón de América y primer ganador de la Copa Intercontinental', 'clubes', 'hard'),
  ('w153', 'CELTIC', 'Club escocés que en 1967 se convirtió en el primer equipo británico en ganar la Copa de Europa', 'clubes', 'hard'),
  ('w154', 'PIOLA', 'Mítico ariete italiano que se mantiene como el máximo goleador histórico de la Serie A con 274 anotaciones', 'jugadores', 'hard'),
  ('w155', 'ACHIQUE', 'Maniobra táctica defensiva sincronizada que consiste en adelantar la línea defensiva para provocar el fuera de juego rival', 'terminos', 'hard'),
  ('w156', 'MUNDIALITO', 'Copa de Oro disputada en Montevideo entre 1980 y 1981 que reunió a selecciones campeonas del mundo para conmemorar 50 años de los Mundiales', 'torneos', 'hard'),
  ('w157', 'BELENENSES', 'Histórico club de Lisboa que rompió en 1946 la hegemonía del Benfica, Sporting y Oporto al coronarse campeón de la liga portuguesa', 'clubes', 'hard'),
  ('w158', 'BOAVISTA', 'Equipo de la ciudad de Oporto que dio la gran campanada al proclamarse campeón de la Primeira Liga portuguesa en la temporada 2000-2001', 'clubes', 'hard'),
  ('w159', 'RAHN', 'Delantero alemán autor del gol del triunfo en la final del Mundial de 1954 ante Hungría', 'jugadores', 'hard'),
  ('w160', 'LABRUNA', 'Legendario goleador de River Plate y máximo anotador en la historia del Superclásico argentino', 'jugadores', 'hard'),
  ('w161', 'ABERDEEN', 'Club escocés que conquistó la Recopa de Europa de 1983 bajo la dirección técnica de Alex Ferguson', 'clubes', 'hard'),
  ('w162', 'KAISERSLAUTERN', 'Club germano que hizo historia en 1998 al coronarse campeón de la Bundesliga siendo un recién ascendido de segunda división', 'clubes', 'hard'),
  ('w163', 'BONIEK', 'Delantero polaco apodado Bello de Noche, estrella de la Juventus y referente de su selección en España 1982', 'jugadores', 'hard'),
  ('w164', 'FERENCVAROS', 'El club más laureado del fútbol húngaro, campeón de la Copa de Ferias en 1965 tras vencer a la Juventus en la final', 'clubes', 'hard'),
  ('w165', 'RIVERA', 'Histórico mediapunta del AC Milan y primer futbolista nacido en Italia en ganar el Balón de Oro (1969)', 'jugadores', 'hard'),
  ('w166', 'GEGENPRESSING', 'Sistema táctico basado en la presión sofocante e inmediata tras la pérdida del balón popularizado en Alemania', 'terminos', 'hard'),
  ('w167', 'GOTEMBURGO', 'Club sueco que sorprendió a Europa al conquistar dos Copas de la UEFA en las décadas de 1980 (1982 y 1987)', 'clubes', 'hard');
